// https://www.compatible-astrology.com/
export const ZodiacCompatibility = {
    aquarius: {
        aquarius:   { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        pisces:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        aries:      { communication: 90, compatibility: 90, sex: 75, description: 'Exciting and fun, the match of Aries and Aquarius has solid potential, though it may be challenging in some specific areas...' },
        taurus:     { communication: 30, compatibility: 50, sex: 60, description: 'Taurus and Aquarius is often a challenging relationship to make work.' },
        gemini:     { communication: 90, compatibility: 90, sex: 90, description: 'Gemini and Aquarius is often a perfect match, and one which often has soulmate potential!' },
        cancer:     { communication: 30, compatibility: 50, sex: 60, description: 'Cancer and Aquarius can be a challenging relationship to make work.' },
        leo:        { communication: 60, compatibility: 70, sex: 90, description: 'Leo and Aquarius is often a challenging and exciting match.' },
        virgo:      { communication: 60, compatibility: 70, sex: 75, description: 'Virgo and Aquarius is often an easy friendship, but can be a harder match to make work as lovers.' },
        libra:      { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        scorpio:    { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        sagittarius:{ communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        capricorn:  { communication: 60, compatibility: 70, sex: 90, description: 'TODO' }
    },
    pisces: {
        aquarius:   { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        pisces:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        aries:      { communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        taurus:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        gemini:     { communication: 60, compatibility: 50, sex: 60, description: 'TODO' },
        cancer:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        leo:        { communication: 60, compatibility: 70, sex: 75, description: 'TODO' },
        virgo:      { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        libra:      { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        scorpio:    { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        sagittarius:{ communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        capricorn:  { communication: 60, compatibility: 70, sex: 90, description: 'TODO' }
    },
    aries: {
        aquarius:   { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        pisces:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        aries:      { communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        taurus:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        gemini:     { communication: 60, compatibility: 50, sex: 60, description: 'TODO' },
        cancer:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        leo:        { communication: 60, compatibility: 70, sex: 75, description: 'TODO' },
        virgo:      { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        libra:      { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        scorpio:    { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        sagittarius:{ communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        capricorn:  { communication: 60, compatibility: 70, sex: 90, description: 'TODO' }
    },
    taurus: {
        aquarius:   { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        pisces:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        aries:      { communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        taurus:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        gemini:     { communication: 60, compatibility: 50, sex: 60, description: 'TODO' },
        cancer:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        leo:        { communication: 60, compatibility: 70, sex: 75, description: 'TODO' },
        virgo:      { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        libra:      { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        scorpio:    { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        sagittarius:{ communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        capricorn:  { communication: 60, compatibility: 70, sex: 90, description: 'TODO' }
    },
    gemini: {
        aquarius:   { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        pisces:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        aries:      { communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        taurus:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        gemini:     { communication: 60, compatibility: 50, sex: 60, description: 'TODO' },
        cancer:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        leo:        { communication: 60, compatibility: 70, sex: 75, description: 'TODO' },
        virgo:      { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        libra:      { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        scorpio:    { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        sagittarius:{ communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        capricorn:  { communication: 60, compatibility: 70, sex: 90, description: 'TODO' }
    },
    cancer: {
        aquarius:   { communication: 30, compatibility: 50, sex: 60, description: 'Cancer and Aquarius can be a challenging relationship to make work.' },
        pisces:     { communication: 90, compatibility: 90, sex: 90, description: 'Cancer and Pisces is a great match, very often with soulmate potential!' },
        aries:      { communication: 30, compatibility: 50, sex: 75, description: 'Aries and Cancer can be challenging relationship to make work.' },
        taurus:     { communication: 90, compatibility: 90, sex: 90, description: 'Taurus and Cancer is a great match, often with soulmate potential!' },
        gemini:     { communication: 60, compatibility: 50, sex: 60, description: 'Gemini and Cancer is often a hard match to make work.' },
        cancer:     { communication: 90, compatibility: 90, sex: 90, description: 'Cancer and Cancer (two partners, both of the Cancer sun sign) is a very romantic match, intensely emotional and highly sexual.' },
        leo:        { communication: 60, compatibility: 70, sex: 75, description: 'Cancer and Leo can be a challenging match.' },
        virgo:      { communication: 90, compatibility: 90, sex: 90, description: 'Cancer and Virgo is often a very good match which brings out the best in each of you.' },
        libra:      { communication: 30, compatibility: 50, sex: 60, description: 'Cancer and Libra can be a challenging relationship to make work.' },
        scorpio:    { communication: 90, compatibility: 90, sex: 90, description: 'Cancer and Scorpio is a match with great emotional intensity, depth and intimacy.' },
        sagittarius:{ communication: 30, compatibility: 50, sex: 75, description: 'Cancer and Sagittarius can be a challenging relationship to make work.' },
        capricorn:  { communication: 60, compatibility: 70, sex: 90, description: 'The match of Cancer and Capricorn is great for a short term fling, but can be more challenging to make work in the longer term, with the risk of a love-hate outcome if not handled carefully.' }
    },
    leo: {
        aquarius:   { communication: 30, compatibility: 50, sex: 60, description: 'Leo and Aquarius is often a challenging and exciting match.' },
        pisces:     { communication: 90, compatibility: 90, sex: 90, description: 'Leo and Pisces can sometimes be a difficult match to make work, though it has a lot of potential.' },
        aries:      { communication: 30, compatibility: 50, sex: 75, description: 'Aries and Leo is a great match, you have much in common and enough subtle differences and competiveness to keep a continuous flame burning.' },
        taurus:     { communication: 90, compatibility: 90, sex: 90, description: 'Taurus and Leo can be a challenging relationship to make work.' },
        gemini:     { communication: 60, compatibility: 50, sex: 60, description: 'Gemini and Leo can be a fun and harmonious match, often resembling a TV comedy show (in a good way!)' },
        cancer:     { communication: 90, compatibility: 90, sex: 90, description: 'Cancer and Leo can be a challenging match.' },
        leo:        { communication: 60, compatibility: 70, sex: 75, description: 'Leo and Leo (two partners both with a Leo sun sign) is a powerful and dramatic match, a playful battle of wills and egos, often with soulmate potential.' },
        virgo:      { communication: 90, compatibility: 90, sex: 90, description: 'Leo and Virgo is a relationship which often presents a challenge and needs compromise on both sides.' },
        libra:      { communication: 30, compatibility: 50, sex: 60, description: 'Leo and Libra is a powerful match, you each bring out the best in each other and share a very similar outlook while being constantly fascinated by each others personality.' },
        scorpio:    { communication: 90, compatibility: 90, sex: 90, description: 'Leo and Scorpio is the type of relationship which will probably make a good movie.' },
        sagittarius:{ communication: 30, compatibility: 50, sex: 75, description: 'Leo and Sagittarius is a great match, often with soulmate potential!' },
        capricorn:  { communication: 60, compatibility: 70, sex: 90, description: 'Leo and Capricorn is an interesting and complex match.' }
    },
    virgo: {
        aquarius:   { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        pisces:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        aries:      { communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        taurus:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        gemini:     { communication: 60, compatibility: 50, sex: 60, description: 'TODO' },
        cancer:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        leo:        { communication: 60, compatibility: 70, sex: 75, description: 'TODO' },
        virgo:      { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        libra:      { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        scorpio:    { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        sagittarius:{ communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        capricorn:  { communication: 60, compatibility: 70, sex: 90, description: 'TODO' }
    },
    libra: {
        aquarius:   { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        pisces:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        aries:      { communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        taurus:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        gemini:     { communication: 60, compatibility: 50, sex: 60, description: 'TODO' },
        cancer:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        leo:        { communication: 60, compatibility: 70, sex: 75, description: 'TODO' },
        virgo:      { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        libra:      { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        scorpio:    { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        sagittarius:{ communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        capricorn:  { communication: 60, compatibility: 70, sex: 90, description: 'TODO' }
    },
    scorpio: {
        aquarius:   { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        pisces:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        aries:      { communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        taurus:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        gemini:     { communication: 60, compatibility: 50, sex: 60, description: 'TODO' },
        cancer:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        leo:        { communication: 60, compatibility: 70, sex: 75, description: 'TODO' },
        virgo:      { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        libra:      { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        scorpio:    { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        sagittarius:{ communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        capricorn:  { communication: 60, compatibility: 70, sex: 90, description: 'TODO' }
    },
    sagittarius: {
        aquarius:   { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        pisces:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        aries:      { communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        taurus:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        gemini:     { communication: 60, compatibility: 50, sex: 60, description: 'TODO' },
        cancer:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        leo:        { communication: 60, compatibility: 70, sex: 75, description: 'TODO' },
        virgo:      { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        libra:      { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        scorpio:    { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        sagittarius:{ communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        capricorn:  { communication: 60, compatibility: 70, sex: 90, description: 'TODO' }
    },
    capricorn: {
        aquarius:   { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        pisces:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        aries:      { communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        taurus:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        gemini:     { communication: 60, compatibility: 50, sex: 60, description: 'TODO' },
        cancer:     { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        leo:        { communication: 60, compatibility: 70, sex: 75, description: 'TODO' },
        virgo:      { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        libra:      { communication: 30, compatibility: 50, sex: 60, description: 'TODO' },
        scorpio:    { communication: 90, compatibility: 90, sex: 90, description: 'TODO' },
        sagittarius:{ communication: 30, compatibility: 50, sex: 75, description: 'TODO' },
        capricorn:  { communication: 60, compatibility: 70, sex: 90, description: 'TODO' }
    }
};